const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),path=require('path');
const html=fs.readFileSync(path.join(__dirname,'index.html'),'utf8');
const script=html.split('<script>')[1].split('</script>')[0];
new vm.Script(script);
const model=script.slice(0,script.indexOf('const $='));
const ctx={};vm.createContext(ctx);
vm.runInContext(model+`\nthis.api={CURRENT,selectPolls,seats,complete,RAW_RESULTS};`,ctx);
const {CURRENT,selectPolls,seats,complete,RAW_RESULTS}=ctx.api;
assert.equal(CURRENT.length,9);
const snapshot=selectPolls(CURRENT,'2026-10-08',35);
assert.equal(snapshot.selected.length,6);
assert.equal(snapshot.selected.find(r=>r.house==='Curia').published,'2026-10-08');
assert.equal(snapshot.selected.find(r=>r.house==='Verian').end,'2026-10-05');
assert.equal(snapshot.selected.find(r=>r.house==='Roy Morgan').end,'2026-09-27');
assert.equal(selectPolls(CURRENT,'2026-10-07',35).selected.find(r=>r.house==='Curia').end,'2026-09-03');
assert.equal(selectPolls(CURRENT,'2026-10-06',35).selected.find(r=>r.house==='Curia').end,'2026-09-03');
const floor=[0,0,0,1,0,1,0], ss=seats(snapshot.v,floor);
assert.equal(ss.parties.reduce((a,b)=>a+b,0),ss.total);
assert.equal(ss.majority,Math.floor(ss.total/2)+1);
assert.deepEqual(Array.from(seats(complete(RAW_RESULTS[2020]),[23,46,1,1,0,1,0]).parties),[33,65,10,10,0,2,0]);
assert.equal(seats([45,40,0,0,0,0,4.9,10.1],[0,0,0,0,0,0,0]).parties[6],0);
assert.ok(seats([45,40,0,0,0,0,4.9,10.1],[0,0,0,0,0,0,1]).parties[6]>0);
assert.throws(()=>selectPolls([{...CURRENT[0],published:'2026-09-01'}],'2026-10-08',35));
assert.equal(script.includes("if(t.dataset.field==='end')r.published=t.value"),false);
const start=script.indexOf('function parliamentSVG('),end=script.indexOf('function renderParliament()',start);
ctx.state={asof:'2026-10-08',scenario:'base',floors:floor};ctx.esc=x=>String(x);
vm.runInContext(script.slice(start,end)+'\nthis.graph=parliamentSVG;',ctx);
const svg=ctx.graph(ss);
assert.equal((svg.match(/<circle[^>]*r="9"/g)||[]).length,ss.total);
assert.ok(!svg.includes('NaN'));
fs.writeFileSync(path.join(__dirname,'parliament.svg'),svg);
console.log(JSON.stringify({checks:'passed',polls:CURRENT.length,included:snapshot.selected.map(r=>r.house),average:Array.from(snapshot.v),seats:ss},null,2));
