const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),path=require('path');
const html=fs.readFileSync(path.join(__dirname,'index.html'),'utf8');
const script=html.split('<script>')[1].split('</script>')[0];
new vm.Script(script);
const model=script.slice(0,script.indexOf('const $='));
const ctx={};vm.createContext(ctx);
vm.runInContext(model+`\nthis.api={CURRENT,selectPolls,seats,complete,RAW_RESULTS};`,ctx);
const {CURRENT:published,selectPolls,seats,complete,RAW_RESULTS}=ctx.api;
const CURRENT=JSON.parse(fs.readFileSync(path.join(__dirname,'tests/polls-fixture.json'),'utf8')).polls;
const {validatePollSheet,canonicalHouse}=require('./poll-data.cjs');
const sheet=validatePollSheet(JSON.parse(fs.readFileSync(path.join(__dirname,'polls.json'),'utf8')));
assert.deepEqual(JSON.parse(JSON.stringify(published)),sheet.polls);
const snapshot=selectPolls(CURRENT,'2026-10-08',35,.5);
assert.equal(snapshot.selected.length,6);
assert.equal(snapshot.selected.find(r=>r.house==='Curia').published,'2026-10-08');
assert.equal(snapshot.selected.find(r=>r.house==='Verian').end,'2026-10-05');
assert.equal(snapshot.selected.find(r=>r.house==='Roy Morgan').end,'2026-09-27');
const rm=snapshot.selected.find(r=>r.house==='Roy Morgan');
assert.equal(snapshot.weights[snapshot.selected.indexOf(rm)],.5);
const equal=selectPolls(CURRENT,'2026-10-08',35,1),excluded=selectPolls(CURRENT,'2026-10-08',35,0);
assert.ok(Math.abs(equal.v[0]-28.5666666667)<1e-6);
assert.ok(Math.abs(snapshot.v[0]-28.3454545455)<1e-6);
assert.ok(Math.abs(excluded.v[0]-28.08)<1e-6);
assert.equal(canonicalHouse('Talbot Mills'),'anacta');
assert.equal(canonicalHouse('1News–Verian'),'verian');
const newPoll={...CURRENT[0],end:'2026-10-09',published:'2026-10-10',v:[30,30,13,8,10,2,5]};
const next=validatePollSheet({schema:1,asof:'2026-10-10',polls:[newPoll,...CURRENT]});
assert.equal(selectPolls(next.polls,next.asof,35).selected.find(r=>r.house==='Curia').end,'2026-10-09');
assert.throws(()=>validatePollSheet({...sheet,polls:[{...CURRENT[0],end:'2026-02-30'}]}));
assert.throws(()=>validatePollSheet({...sheet,polls:[{...CURRENT[0],v:[50,40,20,0,0,0,0]}]}));
assert.throws(()=>validatePollSheet({...sheet,polls:[CURRENT[0],{...CURRENT[0],house:'TPU Curia'}]}));
assert.equal(selectPolls(CURRENT,'2026-10-07',35).selected.find(r=>r.house==='Curia').end,'2026-09-03');
assert.equal(selectPolls(CURRENT,'2026-10-06',35).selected.find(r=>r.house==='Curia').end,'2026-09-03');
const floor=[0,0,0,1,0,1,0], ss=seats(snapshot.v,floor);
assert.equal(ss.parties.reduce((a,b)=>a+b,0),ss.total);
assert.equal(ss.majority,Math.floor(ss.total/2)+1);
assert.deepEqual(Array.from(seats(complete(RAW_RESULTS[2020]),[23,46,1,1,0,1,0]).parties),[33,65,10,10,0,2,0]);
assert.equal(seats([45,40,0,0,0,0,4.9,10.1],[0,0,0,0,0,0,0]).parties[6],0);
assert.ok(seats([45,40,0,0,0,0,4.9,10.1],[0,0,0,0,0,0,1]).parties[6]>0);
assert.throws(()=>selectPolls([{...CURRENT[0],published:'2026-09-01'}],'2026-10-08',35));
assert.equal(script.includes("if(t.dataset.field==='end')r.published=t.value"),false);
const start=script.indexOf('function parliamentSVG('),end=script.indexOf('function renderParliament()',start);
const publishedSnapshot=selectPolls(published,sheet.asof,35,.5),publishedSeats=seats(publishedSnapshot.v,floor);
ctx.state={asof:sheet.asof,scenario:'base',floors:floor,royWeight:.5};ctx.esc=x=>String(x);
vm.runInContext(script.slice(start,end)+'\nthis.graph=parliamentSVG;',ctx);
const svg=ctx.graph(publishedSeats);
assert.equal((svg.match(/<circle[^>]*r="9"/g)||[]).length,publishedSeats.total);
assert.ok(!svg.includes('NaN'));
fs.writeFileSync(path.join(__dirname,'parliament.svg'),svg);
console.log(JSON.stringify({checks:'passed',polls:published.length,included:publishedSnapshot.selected.map(r=>r.house),average:Array.from(publishedSnapshot.v),seats:publishedSeats},null,2));
